### ISSUE TITLE
Ability to choose a different translation server.

### ISSUE THREAD

**Issue by mohdshara** [grisov/quickDictionary#1]
Hi.

Are there currently any good known alternative servers? It looks like this server doesn't support Arabic. It would be nice if there was a combo box of pre-configured alternatives.

**Comment by grisov** [comment]
Hi ;)

In new version added support for expanding the capabilities of the add-on by registering in it other services.
Now there is an opportunity to add other online dictionaries and translation services to the add-on.

The Lexicala online dictionary service has also been added 9894fe35921cdcc8b97a3369d4e288650e83639.
This service supports Arabic language.
The disadvantage of this service is the small limit of requests per day for free users - 300 per day.
Therefore, I advise you to register your own credentials.

The ReadMe file has not been updated yet.
Briefly about new opportunities:
* F1-F2 - switching between different online services.
* NVDA+Y then Q - information about the selected service: name, balance of the daily quota, etc.
* The settings panel has detailed settings for each service.
* H - display of help information.

You can download the add-on here:
https://github.com/grisov/quickDictionary/releases/download/v2.0/quickDictionary-2.0.nvda-addon

Good luck! :)

**Comment by grisov** [comment]
The add-on version has been updated.
The current version can be found in the release section.
Since the ability to add other online services has been implemented in the add-on, I believe that this issue can be closed.

Merry Christmas and Happy New Year!
Oleksandr
